---
apiVersion: v1
kind: Service
metadata:
  name: boateng7-test-flask-service
  labels: boateng7
  env: test
spec:
  type: ClusterIP
  ports:
  - name: http
  selector:
    app: boateng7-test-flask
    username: boateng7
  ports:
  - name: boateng7-test-flask
    port: 5000
    targetPort: 5000 
