

---
apiVersion: v1
kind: Service
metadata:
  name: boateng7-test-redis-service
  labels:
    username: boateng7
    env: test
spec:
  type: ClusterIP
  selector:
    app: boateng7-test-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
