---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boateng7-test-flask-deployment
  labels:
    username: boateng7
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boateng7-test-flask
  template:
    metadata:
      labels:
        app: boateng7-test-flask
        username: boateng7
        env: test
    spec:
      containers:
        - name: flask
          imagePullPolicy: Always
          image: boatengsam/gene:1.0
          env: 
          - name: REDIS_HOST
            value: boateng7-test-redis-service
          ports:
          - name: http
            containerPort: 5000
